//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Assignment__3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends_Shuba
    {
        [Display(Name = "Friend ID")]

        [Required(ErrorMessage = "Friend Id is Required")]

        public int FriendId { get; set; }

        [Display(Name = " Friend Name")]
        [Required(ErrorMessage = "Friend Name Empty not allowed")]

        public string FriendName { get; set; }

        [Display(Name = "Place")]
        [Required]
        [StringLength(25)]
        public string Place { get; set; }
    }
}
