//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_RIDHI_FIFTEENTH
    {
        public int EMPId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
